version: '3'
services:
  proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - backend

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-latest
    expose:
      - "50021:50021"
    networks:
      - internal_network
    tty: true
    restart: unless-stopped 

  backend:
    build: backend/
    ports:
      - "5001:5001"
    networks:
      - internal_network
    tty: true
    depends_on:
      - redis
      - voicevox_engine
  
  redis:
    image: redis
    networks:
      - internal_network

  app:
    build: frontend/
    ports:
      - "3000:3000"
  # TODO 本番環境用ビルドコマンドに変更
    command: ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
  # 開発環境用ホットリロード
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  internal_network:
    driver: bridge