services:
  proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - backend-flask

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-latest
    expose:
      - "50021:50021"
    networks:
      - internal_network
    tty: true
    restart: unless-stopped 

  backend-updater:
    build: 
      context: backend/
      dockerfile: services/updater/Dockerfile
    env_file:
      - .env
    networks:
      - internal_network
    tty: true
    depends_on:
      - redis
      - voicevox_engine

  backend-flask:
    build: 
      context: backend/
      dockerfile: services/flask/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
      - internal_network
    tty: true
    depends_on:
      - backend-updater
  
  redis:
    image: redis
    networks:
      - internal_network

  app:
    build: frontend/
    env_file:
      - .env
    ports:
      - "3000:3000"
  # TODO 本番環境用ビルドコマンドに変更
    command: ["npm", "run", "dev", "--", "-H", "0.0.0.0"]

networks:
  internal_network:
    driver: bridge